version: 2
jobs:
  build:
    docker:
      - image: ruby:2.6.3-alpine
    steps:
      # Install dependencies
      - run: apk update && apk upgrade && apk add git

      - checkout

      # Restore bundle cache
      - restore_cache:
          key: gems-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Run RSpec
      - type: shell
        command: |
          bundle exec rspec --format documentation --color

      # Run rubocop
      - run: bundle exec rubocop -DES
